### ISSUE TITLE
Pythonize totalsedimenterosionMUDsine.m

### ISSUE THREAD

**Issue by collinjroland** [espin-2020/CoastalTeam#2]
Pythonize totalsedimenterosionMUDsine.m

**Comment by rachela-sfei** [comment]
I will start working on this

**Comment by collinjroland** [comment]
Complete, pending review:  https://github.com/collinjroland/CoastalTeam/blob/collinjroland/coastal/totalsediment_erosion.py

**Comment by collinjroland** [comment]
This function is included in total_erosion_calculator.py
